# [1] 넘파이 (NumPy : Numerical Python)
#### 넘파이 배열 ndarray 생성, 변환, 값추출, 행렬 연산 연습

In [4]:
!pip install numpy

   ---------------------------------------- 0.0/15.9 MB ? eta -:--:--
   ------------------------------------- -- 14.9/15.9 MB 72.0 MB/s eta 0:00:01
   ---------------------------------------- 15.9/15.9 MB 62.6 MB/s eta 0:00:00


In [5]:
import numpy as np

## 1-1. ndarray 생성

- np.array(*array_like_data*, dtype=*'data_type'*) [ref](https://numpy.org/doc/stable/reference/generated/numpy.array.html)
- np.arange(*[start], stop, [step]*), np.arange(*start=, stop=, step=*) [ref](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange) 
- np.zeros(*shape*) [ref](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros)
- np.ones(*shape*) [ref](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones)

## 1-2. ndarray 데이터 확인
- ndarray.shape : ndarray의 (행의 수, 열의 수) 튜플
- ndarray.ndim : ndarray 차원
- ndarray.dtype : ndarray 내 데이터 타입
- ndarray.astype(*'data_type'*)
- python type(*data*) : data의 데이터 타입

In [76]:
#1차원 array 생성
arr1d = np.array([1, 2, 3])

# 2차원 array 생성
arr2d = np.array([[1, 2, 3],[4,5,6]])

# 3차원 array 생성
arr3d = np.array([[[1,2,3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [ ]:
# array 요소의 type 지정하여 ndarray 생성
array_float = np.array([1, 2, 3], dtype='float64')


In [7]:
# arange() 메서드 활용
# 0 ~ 9 정수 배열 생성
import numpy as np

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

# [0.0 2.0 4.0 6.0 8.0] ndarray 생성
sequence_array = np.arange(0,10,2,dtype='float')

# [1 3 5 7 9] ndarray 생성
sequence_array = np.arange(start=1,stop=10,step=2)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [8]:
# 요소가 모두 0인 ndarray 생성 (3행 2열 배열)
zero_array = np.zeros((3,2), dtype='int')

In [9]:
# 요소가 모두 1인 ndarray 생성 (3행 2열 배열)
one_array = np.ones((3,2))

## 1-3. 변환 - reshape(), tolist()
- 차원 변환 : ndarray.reshape(*shape*), ndarray.reshape(*row*, *colunm*)
    - 원래 배열과 요소의 수가 다르면 error 발생
    - row, column 중 하나에 -1값을 쓰면 알아서 변환
- python list로 변환 : ndarray.tolist()

In [78]:
# 요소가 10개인 1차원 ndarray
array1 = np.arange(10)

# 2행 5열 2차원 ndarray로 변환
array2 = array1.reshape(2,5)

# 5행 2열 2차원 ndarray로 변환
array3 = array1.reshape(5,2)

In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

In [80]:
#  8개 요소를 갖는 1차원배열 생성 -> 각 요소가 2인 3차원 배열로 변환
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,2)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,2)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


## 1-4. 데이터 세트 선택 (Indexing) : [ ]
- 단일값 추출: [*index*]
- Slicing : [*start*:*stop*:*step*]
- Boolean Indexing : [*Boolean Condition*]
- Fancy Indexing : [*list of index*]
- index, start, end의 값이 음수인 경우 배열의 뒤에서부터 indexing

### 1-4-1. 단일값 추출 : [*index*]

In [6]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(1,10)
print(array1)

# 제일 뒤의 값과 뒤에서 두번째 값 출력
print(array1[-1])
print(array1[-2])

[1 2 3 4 5 6 7 8 9]
9
8


In [ ]:
# 3행 3열의 정수 배열 생성
array2d = np.arange(start=1, stop=10).reshape(3, 3)
print(array2d)

# (0,0) 값 (1,1) 값, (2, 2) 값 출력
print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=1,col=1) index 가리키는 값:', array2d[1,1] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

### 1-4-2. Slicing : [*start*:*stop*:*step*]

In [8]:
# array1에 0부터 11까지의 1차원 배열 생성
array1 = np.arange(12)
print(array1)

# 앞에서 3개 요소 반환
print(array1[:3])

# 앞에서 3번째부터 마지막 요소까지 반환
print(array1[3::])

# 전체 반환
print(array1[::])

# 뒤에서 3번째 부터 반환
print(array1[-3::])

# 앞에서부터 뒤에서 3번째 요소까지 반환
print(array1[:-2:])

print(array1[-3::-1])

# 뒤에서부터 모두 반환
print(array1[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 1 2]
[ 3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 9 10 11]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[11 10  9  8  7  6  5  4  3  2  1  0]


### 1-4-3. Boolean Indexing : [*Boolean Condition*]

In [11]:
array1d = np.arange(start=1, stop=10)
print(array1d)

# 5보다 큰 값만 출력
print(array1d[array1d > 5])

# 5보다 크고 8보다 작은 값만 출력
print(array1d[(array1d >= 5) & (array1d <= 8)])

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[5 6 7 8]


In [12]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


### 1-4-4. Fancy Indexing : [*list of index*]

In [14]:
print(array1d)
# index 5, 1, 3, 2 순서대로 데이터 출력
index = [5, 1, 3, 2]
np_index = np.array(index)
array1d[index]


[1 2 3 4 5 6 7 8 9]


array([6, 2, 4, 3])

### 1-5. 정렬 : sort( )와 argsort( )

- numpy.sort(*ndarray*, axis=) : 원 행렬 변경없음 → 반환값 활용
- ndarray.sort() : 원 행렬 변경 → 반환값 없음
- numpy.argsort(*ndarray*) : 정렬 시의 index 순서 반환

In [23]:
org_array = np.array([ 3, 1, 9, 5])
print(org_array)
org_backup = org_array.copy()
print(org_backup)

# np.sort( )로 정렬 후 원 행렬과 반환값 출력
print(np.sort(org_array))

# ndarray.sort( )로 정렬 후 원 행렬과 반환값 출력
org_array.sort()
print(org_array)
print(org_backup)

# no.argsort()로 인덱스만 반환
print(np.argsort(org_backup))

[3 1 9 5]
[3 1 9 5]
[1 3 5 9]
[1 3 5 9]
[3 1 9 5]
[1 0 3 2]


In [83]:
# 내림차순으로 정렬
sort_array1_desc = np.sort(org_array)[::-1]

# 행렬 내림차순 정렬 시 원본 행렬의 인덱스



#### [연습문제] 이름과 성적이 각각의 ndarray로 주어진 경우 이름을 성적 순서로 출력하기

In [28]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

# 성적을 index로 정렬
score_index = np.argsort(score_array)[::-1]
print(score_index)

# 정렬된 순서대로 해당 이름을 출력
print(name_array[score_index])

# * [::-1]를 스코어인덱스 저기나 '정렬된순서대로해당이름출력' 부분에 넣으면 성적 높은 순으로 나옴(안넣으면 성적낮은순(숫자순)으로 나옴)

[3 1 4 2 0]
['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


# [2] 판다스 (Pandas)
#### DataFrame 기반 데이터 핸들링
1. 생성 및 변환
1. 데이터 확인
1. 결측치 처리
2. 중복값 처리
1. 컬럼 생성, 수정, 삭제
1. 정렬

In [30]:
!pip install pandas

   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 11.6/11.6 MB 90.8 MB/s eta 0:00:00


In [31]:
import pandas as pd

## 2-1. 파일을 DataFrame으로 로딩
- pandas.read_csv(*file_path/url*, sep=, encoding=, ...)
- pandas.read_json(*file_path/url*, encoding=, ...)

In [33]:
# sample_data.csv 로딩
sample_df = pd.read_csv('./data/sample_data.csv')
sample_df

Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

## 2-2. 데이터 확인을 위한 속성 및 메서드
- dataframe.head(*num_row=5*) : 앞 부분 출력
- dataframe.tail(*num_row=5*) : 뒷 부분 출력
- dataframe.shape : 행, 렬의 크기
- dataframe.info() : 데이터 갯수, null값(결측치, NaN) 등 확인
- python len(*dataframe*) : 데이터 갯수
- dataframe.describe() : 기술 통계값
  - 데이터형이 float나 int인 열에만 적용
  - 각 열의 개수(count), 평균(mean), 표준편차(std), 최솟값(min), 최댓값(max) 등의 통계치 확인 가능
- dataframe.value_counts(dropna=True) : 속성값별 갯수

In [34]:
# 앞부분 3열
sample_df.head(3)

Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN

In [35]:
# 뒷부분 3열
sample_df.tail(3)

Name   Age Gender      City
4  Edward   NaN      M   Houston
5   Alice  24.0      F  New York
6   Susan  32.0      F   Houston

In [36]:
# 크기, 갯수, 결측치 확인
print(sample_df.shape, len(sample_df))
sample_df.info()

(7, 4) 7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    7 non-null      object 
 1   Age     5 non-null      float64
 2   Gender  7 non-null      object 
 3   City    6 non-null      object 
dtypes: float64(1), object(3)
memory usage: 352.0+ bytes


In [38]:
# 기술 통계값 확인
sample_df.describe()

Age
count   5.000000
mean   26.200000
std     4.147288
min    22.000000
25%    24.000000
50%    24.000000
75%    29.000000
max    32.000000

In [42]:
# 속성값별 갯수 확인
sample_df['Age'].value_counts(dropna=False)

Age
24.0    2
NaN     2
22.0    1
29.0    1
32.0    1
Name: count, dtype: int64

## 2-3. DataFrame 생성 : pd.DataFrame()
    * pd.DataFrame(*list/ndarray*, columns=)
    * pd.DataFrame(*dictionary*)
        * Key는 컬럼명으로 매핑, Value는 리스트 형(또는 ndarray)

In [86]:
import numpy as np

col_name1=['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)
print('array1 shape:', array1.shape )

# list를 이용해 DataFrame 생성
df_list1 = pd.DataFrame(list1, columns=col_name1)

# ndarray를 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1, columns=col_name1)


array1 shape: (3,)


In [67]:
# 2행x3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환.
col_name2=['col1', 'col2', 'col3']
list2 = [[1, 2, 3], [11, 12, 13]]
array2 = np.array(list2)

# list를 이용해 DataFrame 생성
df_list2 = pd.DataFrame(list2, columns=col_name2)

# ndarray를 이용해 DataFrame 생성
df_array2 = pd.DataFrame(array2, columns=col_name2)

In [87]:
# dictionary를 이용해 DataFrame 생성
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)

## 2-4. DataFrame을 list, dictionary, ndarray로 변환
- dataframe.values : ndarray로 변환
- dataframe.values.tolist() : list로 변환
- dataframe.to_dict(orient=) : dictionary로 변환
  * 'dict' (default) : column -> {index -> value}
  * 'list' : column -> [values]

In [88]:
# DataFrame을 ndarray로 변환 (df_dict)
array3 = df_dict.values

# DataFrame을 리스트로 변환
list3 = df_dict.values.tolist()

# DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list')


## 2-5. 결측치 처리하기
* 결측치 확인 : info(), isnull()
* 결측치 포함 행 삭제 : dataframe.dropna(subset=, inplace=)
    - subset = *List* (지정 된 범위에 null이 있을 경우 Row 삭제)
* 새로운 값으로 채우기 : dataframe.fillna(value, inplace=)
   * 특정 컬럼에 해당하는 값만 채우려는 경우 : DataFrame **[** *name* **]**.**fillna**(...)

In [ ]:
# sample_data.csv을 dataframe으로 로딩하여 결측치 확인
sample_data.csv(file_path/url, sep=, encoding=; ...)

In [46]:
# 결측치 확인 : 컬럼별 결측치 갯수 계산
sample_df.isnull().sum()

Name      0
Age       2
Gender    0
City      1
dtype: int64

In [53]:
sample_df.isnull().any(axis=1)

0    False
1     True
2     True
3    False
4     True
5    False
6    False
dtype: bool

In [54]:
sample_df[sample_df.isnull().any(axis=1)]

Name   Age Gender         City
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
4   Edward   NaN      M      Houston

In [56]:
# 결측치가 있는 행 추출 
null_df = sample_df[sample_df.isnull().any(axis=1)]
null_df

Name   Age Gender         City
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
4   Edward   NaN      M      Houston

In [62]:
# 결측치가 있는 행 삭제
sample_df.dropna(inplace=True)
sample_df.dropna(subset=['City'], inplace=True)

## 2-6. 중복값 처리하기
* 중복값 확인 : duplicated(keep=)
    - keep = True (첫번째 포함)
* 중복값 삭제 : drop_duplicates(subset=, inplace=)
    - subset = *List* (지정 된 범위에 null이 있을 경우 Row 삭제)

In [57]:
# 중복값인 행 확인
sample_df.duplicated(keep=False)

0     True
1    False
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [58]:
# 중복값인 행 추출
du_df = sample_df[sample_df.duplicated(keep=False)]
du_df

Name   Age Gender      City
0  Alice  24.0      F  New York
5  Alice  24.0      F  New York

In [63]:
# 중복값인 행 삭제
sample_df.drop_duplicates(inplace=True)

## 2-7. 컬럼 생성, 수정, 삭제
* dataframe['컬럼명'] = data
* dataframe['컬럼명'] = dataframe 컬럼 간 연산
* drop(*컬럼명 리스트*, axis=1, inplace=)

In [ ]:
# 값이 모두 0인 'Age_0' 칼럼 생성


In [ ]:
# 'Age' 칼럼의 값에 모두 10을 곱한 'Age_by_10' 칼럼 생성


In [ ]:
# 'Age_0' 컬럼 삭제


## 2-8. 정렬

* dataframe.sort_values(by=컬럼리스트, ascending=True/False)

In [ ]:
# 'City' 정보를 기준으로 정렬


# 3. 맷플롯립 (Matplotlib)
1. 데이터 준비 : x 데이터, y 데이터
2. 그래프 생성 : 선 그래프 (Line Plot), 막대 그래프 (Bar Plot)
   * plot(x, y), bar(x, y), barh(x, y)
4. 제목, 레이블, 범례 등 추가
   * title(), xlabel(), ylabel()
6. 출력
   * 화면 : show()
   * 저장 : savefig() → show()를 하지 않아야 함 (화면 출력도 함) 

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# matplotlib 한글 폰트 설정
from matplotlib import font_manager, rc #runtime configuration

font_path = "c:/Windows/Fonts/malgun.ttf"
font_name = font_manager.FontProperties(fname=font_path).get_name()
# 맥인 경우에는 아래와 같이 font_name을 지정
# font_name = 'AppleGothic'
rc('font', family=font_name)

In [ ]:
# 데이터 준비
x = ['A', 'B', 'C']
y = [4, 5, 6]

In [ ]:
# 선 그래프 그리기


In [ ]:
# 막대 그래프 그리기


In [ ]:
# 수평형 막대 그래프 그리기


In [ ]:
# 그래프 파일 저장 
